lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
title: [Jeff Polk, Data Engineer]
description: [My personal GitHub page]
theme: minima